name: "Apply Diff"
on:
  push:
    branches: [ "main" ]
jobs:
  applydiff:
    runs-on: ubuntu-latest
    steps:
    - name: Remove unnecessary files
      run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        github_access_token: ${{ secrets.HEREABOUT_CLI_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - name: CLI Apply Diff
      env:
        AREA_ULID: ${{ secrets.AREA_ULID }}
        POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PW: ${{ secrets.POSTGRES_PW }}
      run: |
        cd nix/cli
        nix develop --ignore-environment --keep AREA_ULID --keep POSTGRES_URL --keep POSTGRES_USER --keep POSTGRES_PW --command cd ../../ && hereabout-cli diff --path elmbridge.dhall
        
