name: "Apply Diff"
on:
  push:
    branches: [ "main" ]
jobs:
  applydiff:
    runs-on: ubuntu-latest
    steps:
    - name: Remove unnecessary files
      run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        github_access_token: ${{ secrets.HEREABOUT_CLI_TOKEN }}
    - uses: DeterminateSystems/magic-nix-cache-action@v2
    - name: CLI Apply Diff
      run: |
        cd nix/cli
        nix develop
        hereabout-cli diff
