name: "Apply Diff"
on:
  push:
    branches: [ "main" ]
jobs:
  applydiff:
    runs-on: ubuntu-latest
    steps:
    - name: Remove unnecessary files
      run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Acquire CLI with Nix
      run: |
        cd nix/cli
        nix develop --option extra-access-tokens github.com=${{ secrets.HEREABOUT_CLI_TOKEN }}
    - name: Apply Diff
      run: |
        hereabout-cli diff
